# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test and Build

on:
  push:
    branches: [ "main" ]

env:
  AWS_ACCOUNT_ID: "var"

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: fastapi
          POSTGRES_PASSWORD: fastapi
          POSTGRES_DB: fastapi_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U fastapi"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - uses: actions/checkout@v4
    - name: Access Environment Variables
      run: |
        echo "AWS_ACCOUNT_ID: ${{ env.AWS_ACCOUNT_ID }}"
        echo "AWS_REGION: ${{ secrets.AWS_REGION }}"
        echo "AWS_ROLE_NAME: ${{ env.AWS_ROLE_NAME }}"
    
